apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch-kibana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/venkatasaikrishna316/venkatasaikrishna316.git # Replace with your repo URL
    path: elasticsearch
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-agent
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/venkatasaikrishna316/venkatasaikrishna316.git # Replace with your repo URL
    path: grafana-agent
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true