apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-agent-config
data:
  agent.yaml: |
    metrics:
      global:
        scrape_interval: 15s
      configs:
      - name: kubernetes
        remote_write:
          - url: https://prometheus-us-central1.grafana.net/api/prom/push
            basic_auth:
              username: <GRAFANA_CLOUD_USER_ID> # Replace with your Grafana Cloud user ID
              password: <GRAFANA_CLOUD_API_KEY> # Replace with your Grafana Cloud API key
        scrape_configs:
          - job_name: 'kubernetes-pods'
            kubernetes_sd_configs:
              - role: pod
            relabel_configs:
              - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
                action: keep
                regex: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-agent
  template:
    metadata:
      labels:
        app: grafana-agent
    spec:
      containers:
      - name: grafana-agent
        image: grafana/agent:v0.24.0
        args:
          - "-config.file=/etc/agent/agent.yaml"
        volumeMounts:
          - name: config
            mountPath: /etc/agent
      volumes:
        - name: config
          configMap:
            name: grafana-agent-config